version: "3"

networks:
  backend:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - static:/static/
      - media:/media/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  django:
    build: ./docker/uwsgi
    volumes:
      - ./django:/app
      - static:/static
      - media:/media/
      - ./docker/uwsgi/uwsgi.ini:/etc/uwsgi/uwsgi.ini
    environment:
      - FLAG=FAKE{testflag}
      - ADMIN_PASSWORD=pass
    networks:
      - backend
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=develop
      - POSTGRES_PASSWORD=test
    networks:
      - backend
  redis:
    image: redis:latest
    networks:
      - backend
  django-rq:
    build: ./docker/rq
    volumes:
      - ./django:/app
    networks:
      - backend

volumes:
  static:
    driver: local
  media:
    driver: local
